# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=150, unique=True)),
                ('fecha_pub', models.DateField()),
                ('foto', models.URLField(max_length=250)),
                ('descripcion', models.TextField()),
                ('rating', models.FloatField()),
                ('genero', models.CharField(choices=[('CM', 'Comedia'), ('TR', 'Terror'), ('DR', 'Drama')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentario', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
