# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170506_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentario',
            new_name='comentario',
        ),
    ]
